const assert = require("node:assert/strict");
const { createStorageService } = require("../js/storage/local-storage.js");
const { createPersonalChangesService } = require("../js/core/personal-changes.js");
const { getPersonalMonthSchedule } = require("../js/core/monthly-schedule.js");
class MemoryStorage { constructor() { this.data = new Map(); } getItem(key) { return this.data.get(key) ?? null; } setItem(key, value) { this.data.set(key, String(value)); } removeItem(key) { this.data.delete(key); } }
let passed = 0; let failed = 0; function test(name, fn) { try { fn(); passed++; console.log(`PASS ${name}`); } catch (error) { failed++; console.error(`FAIL ${name}\n${error.stack}`); } }
const service = createPersonalChangesService(createStorageService(new MemoryStorage()));
test("1 — outubro contém Pronto Socorro oficial em 05/10", () => { const october = getPersonalMonthSchedule("marco", 2026, 10, service); const day = october.find((item) => item.date === "2026-10-05"); assert.equal(day.activities[0].title, "Pronto Socorro"); assert.equal(day.activities[0].startTime, "07:00"); });
test("2 — edição pessoal aparece no mês", () => { service.updateActivity("marco", "2026-10-05", "r2-d-monday-01", { title: "Plantão PS PED" }); assert.equal(getPersonalMonthSchedule("marco", 2026, 10, service).find((item) => item.date === "2026-10-05").activities[0].title, "Plantão PS PED"); });
test("3 e 4 — mover e criar aparecem no destino mensal", () => { service.createPersonalActivity("marco", "2026-10-06", { id: "personal-meeting", title: "Reunião", startTime: "17:00", endTime: "18:00", location: "HC", preceptor: null }); service.moveActivity("marco", "2026-10-06", "2026-10-07", { id: "personal-meeting", title: "Reunião", startTime: "17:00", endTime: "18:00", location: "HC", preceptor: null }); const october = getPersonalMonthSchedule("marco", 2026, 10, service); assert.equal(october.find((item) => item.date === "2026-10-06").activities.some((a) => a.title === "Reunião"), false); assert.equal(october.find((item) => item.date === "2026-10-07").activities.some((a) => a.title === "Reunião"), true); });
test("5 — exclusão não aparece no mês pessoal", () => { service.deleteActivity("marco", "2026-10-05", "r2-d-monday-01"); assert.equal(getPersonalMonthSchedule("marco", 2026, 10, service).find((item) => item.date === "2026-10-05").activities.some((a) => a.id === "r2-d-monday-01"), false); });
test("7 — setembro desabilita 01–20 e valida dia 21", () => { const september = getPersonalMonthSchedule("marco", 2026, 9, service); assert.equal(september.find((item) => item.date === "2026-09-20").status, "OUT_OF_SCHEDULE_RANGE"); assert.equal(september.find((item) => item.date === "2026-09-21").status, "OK"); });
test("8 — fevereiro termina no dia 28, março está fora", () => { const february = getPersonalMonthSchedule("marco", 2027, 2, service); assert.equal(february.length, 28); assert.equal(february[27].status, "OK"); assert.equal(getPersonalMonthSchedule("marco", 2027, 3, service)[0].status, "OUT_OF_SCHEDULE_RANGE"); });
console.log(`\n${passed} passed, ${failed} failed`); if (failed) process.exit(1);
